-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 28, 2021 at 11:45 AM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `set`
--

-- --------------------------------------------------------

--
-- Table structure for table `book_data`
--

CREATE TABLE `book_data` (
  `book_id` int(11) NOT NULL,
  `book_title` varchar(100) NOT NULL,
  `book_pdf_url` varchar(300) NOT NULL,
  `image_url` varchar(300) NOT NULL,
  `category` text NOT NULL,
  `size` varchar(100) NOT NULL,
  `pages` varchar(200) NOT NULL,
  `language` text NOT NULL,
  `Author_name` varchar(200) NOT NULL,
  `reviews` varchar(200) NOT NULL,
  `ratings` int(100) NOT NULL,
  `Desciption` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32;

--
-- Dumping data for table `book_data`
--

INSERT INTO `book_data` (`book_id`, `book_title`, `book_pdf_url`, `image_url`, `category`, `size`, `pages`, `language`, `Author_name`, `reviews`, `ratings`, `Desciption`) VALUES
(1, 'Last Call', 'https://drive.google.com/file/d/1sHqj7SH6p3_2BdxDLo9yDQxaADtCcEoS/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619161508/Srikanthi/Last_Call_Image_lbdx6l.jpg', 'Comic', '1.98 mb', '120', 'English', 'Calyton Alice', '136', 4, 'The next step in their lives seems preordained?toasts, veils, and the aisle of rose petals. But when an accident on a photo shoot in Southeast Asia brings Caroline the most terrifying phone call she could ever imagine, she has to ask whether ?till death do us part? is a more realistic prospect than faces most couples.'),
(2, 'Seduction and Snacks', 'https://drive.google.com/file/d/1Ir2HRlJQPlbycxsTPH8XWGEbs4bPGHbs/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619161597/Srikanthi/Seduction_and_Snacks_image_wbceuj.jpg', 'Comic', '1.24 mb', '246', 'English', 'Tara Sevic', '89', 5, 'Claire is a twenty-something, single mom that grudgingly helps her best friend sell sex toys while she attempts to make enough money to start her own business to give her foul-mouthed, but extremely loveable (when he\'s asleep) toddler a better life.'),
(3, 'Shame on Me', 'https://drive.google.com/file/d/1qNqYgSLsi_rnJ3NFdwNqrIPVK9r5SB3n/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162308/Srikanthi/Shame_on_Me_Image_d1njyd.jpg', 'Comic', '739 kb', '118', 'English', 'Sevic Tara', '765', 4, 'Shame on Me is the second installment of Tara Sivec\'s Fool Me Once series. This series follows three friends who have been wronged by the men in their life and they decide to help other women by opening a private investigation firm.'),
(4, 'Willing Captive', 'https://drive.google.com/file/d/1AoDih6ez1-xhBzO-fvELJhCmLUNAPGAM/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162473/Srikanthi/willing-captive_image_muqsqh.jpg', 'Comic', '965 kb', '312', 'English', 'Aurora Belle', '97', 5, 'Delilah ?Lily? Flynn is used to her drab existence. Lily?s been living it for twenty two years.Her boring life is suddenly turned on its head when she?s rudely kidnapped from her bedroom.'),
(5, 'Shame on You', 'https://drive.google.com/file/d/1pI98PxE-6k4eueuMAIE8soapQfPKH3Ao/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162490/Srikanthi/Shame_on_You_Image_wslkgp.jpg', 'Comic', '768 mb', '117', 'English', 'Sevic Tara', '357', 4, 'War veteran Kennedy O?Brien is in the business of sticking it to the man?or at least any man who tries to cross a woman. After she returned home from Afghanistan and caught her husband in bed with the nanny, Kennedy lost her faith in men and started Fool Me Once Investigations with her two best friends. After all, there?s no better bounty hunter than a woman scorned.'),
(6, 'Cruel Price', 'https://drive.google.com/file/d/1FJUHcGrzEbgGteyErLVibliL1_ZWbEmr/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162525/Srikanthi/Cruel_Prince_Image_buwrsy.jpg', 'Romance', '1.39 mb', '311', 'English', 'Ashley Jade', '125', 4, 'I never thought I\'d step foot in Royal Manor again.But four years later, here I am...back to finish my senior year at Royal Hearts Academy.'),
(7, 'Romancing the Duke', 'https://drive.google.com/file/d/10o9uQkIsTlfIqs_RbR-LhSygwo7EfVA_/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162545/Srikanthi/Romancing_the_duke_image_iemgu1.jpg', 'Romance', '1.81 mb', '239', 'English', 'Dare Tessa', '267', 4, 'As the daughter of a famed author, Isolde Ophelia Goodnight grew up on tales of brave knights and fair maidens. She never doubted romance would be in her future, too. The storybooks offered endless possibilities.'),
(8, 'In the bed with the Boss', 'https://drive.google.com/file/d/1ZGEyQ5qJWI9BFmBGamr-XXYVRtkY00_N/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162630/Srikanthi/In_the_bed_with_the_Boss_image_wcy7oe.jpg', 'Romance', '2.53 mb', '673', 'English', 'Sarah Morgan', '398', 4, 'When the boss... gets unbuttoned! Deep in the Brazilian rainforest, innocent English rose Grace has come to reclusive billionaire Rafael\'s lair to save her business. With just minutes to persuade him to help ? her only other option is to settle her debts in his bed!'),
(9, 'Katie in Love', 'https://drive.google.com/file/d/1ZGEyQ5qJWI9BFmBGamr-XXYVRtkY00_N/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162657/Srikanthi/Katie_In_Love_Image_j9n3ht.jpg', 'Romance', '1.09 mb', '231', 'English', 'Chloe Thurlow', '197', 4, 'Katie Boyd has nothing in common with Tom Bridge, the volunteer doctor she meets at a party ? except in bed she finds a passion to match her own. Tom is intense, puzzling, a man who cares about others and compels Katie to question her own life drifting through the hip clubs and London party scene.'),
(10, 'Romancing Mister Bridgeriton', 'https://drive.google.com/file/d/1e-49ENtP-pe5ZChbayp2f3SgKaQUoPsX/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619342823/Srikanthi/Romancing_Mister_Bridgeriton_image_oumppg.jpg', 'Romance', '1.13 mb', '294', 'English', 'Quinn Julia', '498', 4, '\"Romancing Mister Bridgerton\" by Julia Quinn is about a young lady who lives in London in the early 1800s. Penelope has loved Colin since she was 16. Now, years later, she was decidedly a spinster. She had come to terms with the fact that the two of them are not suited, but she still appreciates their friendship.'),
(11, 'Big Sick Heart', 'https://drive.google.com/file/d/1e-49ENtP-pe5ZChbayp2f3SgKaQUoPsX/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162682/Srikanthi/Big_Sick_Heart_t2i4zu.jpg', 'Detective & Mystery', '856 kb', '233', 'English', 'Mike Markel', '768', 4, 'Seagate\'s own life is consumed by her alcoholism, but nobody believes what she does when she finally catches the killer. Bad decisions have finally caught up with police detective Karen Seagate. Her drinking has destroyed her marriage and hurt her job performance.'),
(12, 'Pulp Crime', 'https://drive.google.com/file/d/1iOf8dBhO3GEI2aSjVdAl-9jwClAkwWAm/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162705/Srikanthi/Pulp_Crime_Image_eftgq6.jpg', 'Detective & Mystery', '26.0 mb', '6344', 'English', 'Group of authors, custom book cover by Jerry eBooks', '543', 5, 'The pulp fiction began early in the 20th century and its heyday was in the 1920s and 30s when hundreds upon hundreds of quickly written titles were released each year promising adventure, danger and romance for anyone brave enough to open up the dramatic covers. This was not literature, this was entertainment, and many authors and publishers pushed the envelope in terms taste, with lurid covers and ? sometimes ? even more lurid writing.Th'),
(13, 'Silent Voices', 'https://drive.google.com/file/d/1iOf8dBhO3GEI2aSjVdAl-9jwClAkwWAm/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162729/Srikanthi/Silent_Voives_Image_kryqt5.jpg', 'Detective & Mystery', '1.40 mb', '379', 'English', 'Patricia Gibney', '287', 5, 'When twenty-five-year-old Rachel Mullen is discovered murdered in her own bed by her devastated twin sister, the morning after a glittering party, it?s a chilling new case for Detective Lottie Parker. Rachel?s freckled face is bruised and broken, a shard of glass placed in her throat? Faced with such a horrifying murder, Lottie wastes no time in pursuing every clue.'),
(14, 'The Sherlock Homes', 'https://drive.google.com/file/d/1q9YxYwAwqf6SrDf8tSuPlU8VwUm40x8k/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162757/Srikanthi/The_Sherlock_Homes_Image_wscbmf.jpg', 'Detective & Mystery', '2.03 mb', '168', 'English', 'Ransom Riggs', '987', 4, 'Referring to himself as a \"consulting detective\" in the stories, Holmes is known for his proficiency with observation, deduction, forensic science, and logical reasoning that borders on the fantastic, which he employs when investigating cases for a wide variety of clients, including Scotland Yard.'),
(15, 'Silent Ridge', 'https://drive.google.com/file/d/1NJNRxK_SG8L4xLrePGwGb045QrI7i0Zo/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162780/Srikanthi/Silent_Ridge_Image_kemcpc.jpg', 'Detective & Mystery', '944 kb', '231', 'English', 'Gregg Oslen', '765', 4, 'Detective Megan Carpenter is no stranger to horrifying crime scenes, but when she arrives at the home of a woman whose body has been brutalized, Megan is shocked to discover that she knows the victim. Monique Delmont helped Megan when she was in danger years ago.'),
(16, 'Blue Lily, Lily Blue', 'https://drive.google.com/file/d/1nj2bNgDUFovp6cqk2Yi1ycBbSryo_dm2/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162806/Srikanthi/Blue_Lily_Lily_Blue_Image_wtrnbz.jpg', 'Fantasy', '1.08 mb', '257', 'English', 'Maggie Stiefvatar', '287', 4, 'Blue Lily, Lily Blue is the third of the Raven Boys series. Blue is the daughter of a physic, and has grown up believing that kissing her true love will end in his death. She has no powers of her own, except for the fact that she amplifies the reading which her guardians Calla and Persephone do.'),
(17, 'Shadows of Self', 'https://drive.google.com/file/d/18oE55VGFC7ounq1s4KazxF0eefY49XmH/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619162866/Srikanthi/Shadows_of_Self_sjtibz.jpg', 'Fantasy', '6.21 mb', '401', 'English', 'Brandon Sanderson', '876', 5, 'In a flashback, Waxillium Ladrian first meets his future wife Lessie on a bounty hunt, where they work together to bag a powerful crime boss. In the present, it is one year since the defeat of the Vanishers. Wax and Marasi have learned of the art of Hemalurgy from the book given to them by Ironeyes.'),
(18, 'The Baazar of Bad Dreams', 'https://drive.google.com/file/d/1T6_UlgsHsa7XDR7KORogsoLsnvuAqO-7/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619342490/Srikanthi/The_Bazaar_of_Bad_Dreams_Image_wqydv8.jpg', 'Fantasy', '1.79 mb', '429', 'English', 'Stephen King', '456', 5, 'There are thrilling connections between stories; themes of morality, the afterlife, guilt, what we would do differently if we could see into the future or correct the mistakes of the past. ?Afterlife? is about a man who died of colon cancer and keeps reliving the same life, repeating his mistakes over and over again.'),
(19, 'The Children of Hurin', 'https://drive.google.com/file/d/1XEC2DAo_6osFy0rtq2Br35mjtt3ZwX2o/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619342581/Srikanthi/The_Children_of_Hurin_Image_eydhjn.jpg', 'Fantasy', '3.24 mb', '223', 'English', 'Tolkien Christopher', '954', 4, 'The lands of Middle-earth were populated by Men and other humanoid races: Elves, Dwarves, and Orcs, as well as divine beings, Valar and Maiar. The story concentrates on a man of the House of Hador, T?rin Turambar, and his sister Ni?nor N?niel, who are cursed along with their father H?rin by the Dark Lord Morgoth.'),
(20, 'Timat\'s Wrath', 'https://drive.google.com/file/d/1FTH5jWWyb7c8dBQFKhS194y1fsHPeDWL/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619342703/Srikanthi/Timat_s_Wrath_image_d6hyjk.jpg', 'Fantasy', '1.86 mb', '464', 'English', 'James S.A. Corey', '267', 5, 'The eighth book in the NYT bestselling Expanse series, Tiamat\'s Wrath finds the crew of the Rocinante fighting an underground war against a nearly invulnerable authoritarian empire, with James Holden a prisoner of the enemy. Thirteen hundred gates have opened to solar systems around the galaxy.'),
(21, 'Castling the King', 'https://drive.google.com/file/d/1Oq4z5A4ET_Zc-YERD3mW0gmXFZ6XZ_J9/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163000/Srikanthi/Castling_the_King_Image_j4jeza.jpg', 'Historical Fiction', '721 kb', '125', 'English', 'Martin Archer', '235', 4, 'This is another of the books in an exciting and action-packed saga about an English serf who rose to become the captain of a company of English archers and fought his way to riches beyond his wildest dreams?and forever changed medieval and modern England.'),
(22, 'Historical Lovecraft', 'https://drive.google.com/file/d/15GAgeDRTYngKz0j0EAil3hi1UyDxebEm/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163057/Srikanthi/Historical_Lovecraft_Image_ahudoa.jpg', 'Historical Fiction', '0.98 mb', '294', 'English', 'Silva, R.Stiles', '567', 5, 'Historical Lovecraft, a unique anthology blending historical fiction with horror, features 26 tales spanning centuries and continents. ... These are tales that reimagine history and look into the past through a darker glass.'),
(23, 'Olympiad, an Historical Novel', 'https://drive.google.com/file/d/15GAgeDRTYngKz0j0EAil3hi1UyDxebEm/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163027/Srikanthi/Olympiad_image_hdtw4x.jpg', 'Historical Fiction', '1.18 mb', '207', 'English', 'Holt Tom', '643', 4, 'This historical novel takes as its basis the fact that 2776 years ago a group of men ran between two piles of stones, and invented history. If, that is, history can be believed. All we know now is the name of the man who won the race in the first ever Olympic Games in 776 BC.'),
(24, 'Jaffa Beach Historical Fiction', 'https://drive.google.com/file/d/1kRdP8suBe4ljh5p3gr0whvXC90u3lANe/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163082/Srikanthi/Jaffa_Beach_Image_qjbckp.jpg', 'Historical Fiction', '1.56 mb', '336', 'English', 'Fedora', '178', 5, 'This is a love story set in the volatile context of the founding of the State of Israel, and the concomitant rise of the Palestinian longing for a homeland. Horowitz brilliantly finds the common humanity of both Arabs and Jews. Her novel is of epic proportions, spanning many decades and three generations.'),
(25, 'The Mammoth Book of Historical Crime Fiction', 'https://drive.google.com/file/d/1FgKHp-kg7ABChQ29wlqfDhU1DVsjlnGB/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163105/Srikanthi/The_Mammoth_Book_of_Historical_Crime_Fiction_Imag_yd1z1f.jpg', 'Historical Fiction', '2.25 mb', '476', 'English', 'Mike Ashley', '497', 5, 'Our dark past brought to life by leading contemporary crime writers. A new generation of crime writers has broadened the genre of crime fiction, creating more human stories of historical realism, with a stronger emphasis on character and the psychology of crime.'),
(26, 'Angela Davis', 'https://drive.google.com/file/d/1fEaU1xyWhheCo98WrqsJ0xqPExEIjAbh/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163139/Srikanthi/Angela_Davis_Image_kdvmyl.jpg', 'Autobiography', '2.58 mb', '376', 'English', 'Angela Y.Davis', '560', 4, 'The political activist reflects upon the people and incidents that have influenced her life and commitment to global liberation of the oppressed'),
(27, 'Autobiography of a Yogi', 'https://drive.google.com/file/d/1Vp6RTrH93Dt7BVdQDKP3son2AHPYhFP6/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163162/Srikanthi/Autobiography_of_a_Yogi_Image_bbobhw.jpg', 'Autobiography', '4.66 mb', '517', 'English', 'Paramahansa Yogananda', '981', 4, 'Autobiography of a Yogi describes the life of Paramahansa Yogananda begining with his childhood, finding his guru Swami Sri Yukteswar Giri, becoming a monk and practicing Kriya Yoga meditation and his travels across America to spread his teachings.'),
(28, 'My Silent War', 'https://drive.google.com/file/d/1s6PQRKrmUE6NYwuPZnmmlC5AI3u85CdS/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163188/Srikanthi/My_silent_war_image_bs7ru1.jpg', 'Autobiography', '1.32 mb', '201', 'English', 'Kim Philby', '642', 4, 'In the annals of espionage, one name towers above all others: that of H.A.R. ?Kim? Philby, the ringleader of the legendary Cambridge spies. A member of the British establishment, Philby joined the Secret Intelligence Service in 1940, rose to the head of Soviet counterintelligence, and, as MI6?s liaison with the CIA and the FBI, betrayed every secret of Allied operations to the Russians, fatally compromising covert actions to roll back the Iron Curtain in the early years of the Cold War.'),
(29, 'The Autobiography of Martin Luther King', 'https://drive.google.com/file/d/1PUmEP-vovrWRrLFJF0T66pTKiIeUqVGv/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619342397/Srikanthi/Martin_Luther_King_autobiography_Image_fifdmz.jpg', 'Autobiography', '5.16 mb', '442', 'English', 'Martin Luther King', '965', 4, 'Written in his own words, this history-making autobiography is Martin Luther King: the mild-mannered, inquisitive child and student who chafed under and eventually rebelled against segregation; the dedicated young minister who continually questioned the depths of his faith and the limits of his wisdom; the loving husband and father who sought to balance his family?s needs with those of a growing, nationwide movement'),
(30, 'Elon Musk : The Unauthorized Autobiography', 'https://drive.google.com/file/d/1JfkBYf6eiMB72TswzE3HuPy3jNxm-KTv/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163267/Srikanthi/Elon_Musk_Image_g9zwrj.jpg', 'Autobiography', '1.03 mb', '302', 'English', 'J.T. Owens', '623', 5, 'Elon Musk: The Unauthorized Autobiography chronicles his life and the history and philosophy behind Tesla, SpaceX, PayPal, The Boring Company, Neuralink, and more. Musk offers a comprehensive vision on how we can change the course of our civilization and move humanity towards a sustainable future... and on to Mars.'),
(31, 'Axis', 'https://drive.google.com/file/d/1q55hPaBBjEQWWeN3-GXkNoCFd12jufG1/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163398/Srikanthi/Axis_Image_ewainw.jpg', 'Science Fiction', '1.06 mb', '325', 'English', 'Robert Charles Wilson', '834', 5, 'Axis takes place on the new planet introduced at the end of Spin, a world the Hypotheticals engineered to support human life and connected to Earth by way of the Arch that towers hundreds of miles over the Indian Ocean.'),
(32, 'Why We Buy', 'https://drive.google.com/file/d/1IddLQjuk11JiomagP71eUgRdHU1iHWCi/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163426/Srikanthi/why_We_Buy_Image_lojhdr.jpg', 'Science Fiction', '715 kb', '188', 'English', 'Paco Underhill', '723', 4, 'Paco Underhill, author of ?Why We Buy?, argues that people buy things not because they\'re useful and sensible but because they make them feel good. His book has been updated for the Internet age to include more recent findings. Underhill is an environmental psychologist who founded Envirosell, Inc.'),
(33, 'The Fifth Science', 'https://drive.google.com/file/d/1_tbmlPLj5DHaUMa242XvNhn0KqFvTtd2/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163448/Srikanthi/The_Fifth_Science_Image_fjkieb.jpg', 'Science Fiction', '1.25 mb', '271', 'English', 'Exurb 1 a', '198', 4, 'The Fifth Science is a collection of 12 stories, beginning at the start of. ... Then there was the fifth science. And that killed the empire stone dead. The Fifth Science is a collection of 12 stories, beginning at the start of the Galactic Human Empire and following right through to its final days.'),
(34, 'Broken Stars', 'https://drive.google.com/file/d/1j6gOQez_CawSq0SgoxzmDNrRZYGjKNSn/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163475/Srikanthi/Broken_Stars_Image_xod1g3.jpg', 'Science Fiction', '3.22 mb', '355', 'English', 'Ken Liu', '843', 4, 'The book is about Lilac LaRoux, top of the top in space social class and making her first independent journey across the universe on her father\'s star ship, the Icarus, and Tarver Merendsen, a decorated soldier who has no business speaking to, or even making eye contact with, anyone of Lilac\'s status.'),
(35, 'Werewolves', 'https://drive.google.com/file/d/1IQnXpn7UIc-6LcjVqwQvkBMzTK56lt7c/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163497/Srikanthi/Werewolves_Image_zmgkvt.jpg', 'Science Fiction', '1.53 mb', '340', 'English', 'one Elliot O\'Donnell', '176', 4, 'This is the product of years of research, with two of the best known werewolf authors of history contributing to this compilation. Two books in one: \"Book of Werewolves\" and \"Werewolves.\" Learn all about werewolf mythology, the history of werewolves, and the lore behind becoming a werewolf.'),
(36, 'Artisian Vegan Cheese', 'https://drive.google.com/file/d/1sdRxFvfhkcL6skW-j62reBOeddnkz8k6/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163524/Srikanthi/Artisan_vegan_cheese_Image_v96uuo.jpg', 'Cook Books', '1.83 mb', '257', 'English', 'Schinner', '935', 4, 'Gourmet restaurateur and vegan food expert Miyoko Schinner shares her secrets for making homemade nondairy cheeses that retain all the complexity and sharpness of their dairy counterparts while incorporating nutritious nuts and plant-based milks. Miyoko shows how to tease artisan flavors out of unique combinations of ingredients, such as rejuvelac and nondairy yogurt, with minimal effort.'),
(37, 'Modern Sauces\'', 'https://drive.google.com/file/d/1ngZVvNMdpvKdvxd1VrBsNEYWqVjfzNQ-/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163554/Srikanthi/Modern_Sauces_Book_Image_ngvyvl.jpg', 'Cook Books', '3.51 mb', '440', 'English', 'Martha', '186', 5, 'This is the book for cooks who want to take their cooking to a whole new level. Martha Holmberg was trained at La Varenne and is an award-winning food writer.'),
(38, 'The Basics : A Really useful cookbook', 'https://drive.google.com/file/d/14mqaMx0W5ac76J0dkMN7U0Y5wRrKZ89K/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163584/Srikanthi/The_Basics_A_really_Useful_Cook_Book_Image_mxw3fx.jpg', 'Cook Books', '3.61 mb', '607', 'English', 'Anthony', '297', 4, 'Including hundreds of easy to follow recipes with simple ingredients for fast everyday meals, this definitive cookbook offers home cooks a comprehensive guide to getting it right in the kitchen.'),
(39, 'The Illustrated Cook\'s Book of Ingredients', 'https://drive.google.com/file/d/1-S_IG9liG5_pD4un52qf88XJ7NOuXMXn/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163607/Srikanthi/The_Illustrated_Cook_s_Book_of_Ingredients_ixjwjo.jpg', 'Cook Books', '119 mb', '546', 'English', 'DK Publishing', '145', 4, 'Featuring useful information on buying, ripening, storing, and working with unusual ingredients, The Illustrated Cook\'s Book of Ingredients serves as an invaluable reference for food lovers and cooks intent on making the most of all the ingredients available today.'),
(40, 'How - to Real Indian Cooking Authentic Home Recipes', 'https://drive.google.com/file/d/1Fb3923zzXqxt9vbUzorbKxXfo6lIMRVf/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619163646/Srikanthi/How-to_Real_Indian_Cooking_Authentic_Home_Cooking_Recipes_uaiam1.jpg', 'Cook Books', '1.19 mb', '64', 'English', 'Chef Vishal Singh', '84', 5, 'One thing is to enjoy an Indian meal at a restaurant, but it is a whole other world having to cook it on your own!Making great food is more than buying a list of ingredients and following a list of directions. It is about knowing those little tips and tricks that you discover, once you have made it a bunch of times.'),
(41, 'Guild master\'s the guide to ravnica', 'https://drive.google.com/file/d/1MK4WeKsdKRceAGOBWEVu_OdwJqkERXx6/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165334/Maahir/guild_masters_guide_to_ravnica_nm6l69.jpg', 'action and adventures', '63.7 mb', '258', 'English', 'Wizards rpg team', '121', 5, 'Guildmasters\' Guide to Ravnica is a 256-page campaign and adventure guide for using the Ravnica setting, from the collectible card game Magic: The Gathering, in the 5th edition. The book includes a ninety page overview of \"the ten guilds of Ravnica along with the Tenth District where most of the guilds operate.'),
(42, 'Harry potter and the cursed child', 'https://drive.google.com/file/d/1wDagf_WvxKRYB8ckYUtDVC5YrXX-OnAX/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165360/Maahir/harry_potter_and_the_cursed_child_wrlt5z.jpg', 'action and adventures', '1.43 mb', '334', 'English', 'j.k rowling', '996', 5, 'Harry Potter and the Cursed Child is a 2016 British two-part play written by Jack Thorne based on an original story by J. K. Rowling, John Tiffany, and Thorne. Previews of the play began at the Palace Theatre, London, on 7 June 2016, and it premiered on 30 July 2016.'),
(43, 'Harry potter and the halfblood prince', 'https://drive.google.com/file/d/1ee4Ne3YjYnd2eDh4w_BATXYlug6ZDww8/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165419/Maahir/harry_potter_and_the_half_blood_prince_fdsa7n.jpg', 'action and adventures', '2.57 mb', '410', 'English', 'j.k rowling', '967', 5, 'Harry Potter and the Half-Blood Prince is a 2009 fantasy film directed by David Yates and distributed by Warner Bros. Pictures. ... It is based on J. K. Rowling\'s 2005 ...'),
(44, 'Harry potter and the secret chamber', 'https://drive.google.com/file/d/1mMjIlPhhb_hCRM8Flmck2NVN17mtwvlw/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165436/Maahir/harry_potter_and_the_chamber_of_secrects_geekxe.jpg', 'action and adventures', '841 kb', '294', 'English', 'j.k. rowling', '945', 5, 'Its story follows Harry Potter\'s second year at Hogwarts School of Witchcraft and Wizardry as the Heir of Salazar Slytherin opens the Chamber of Secrets, unleashing a monster that petrifies the school\'s denizens.'),
(45, 'Tolkiens world', 'https://drive.google.com/file/d/12xTZ_PkN8PAnzX-xPeAT9T6GtVtOt1l0/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165456/Maahir/tolkiens_world_n3rerc.jpg', 'action and adventures', '44.6 mb', '157', 'English', 'j.rr.tolkien', '230', 4, 'Tolkien is a 2019 American biographical drama film directed by Dome Karukoski and written by David Gleeson and Stephen Beresford. It is about the early life of English professor J. R. R. Tolkien, author of The Hobbit and The Lord of the Rings, as well as notable academic works.'),
(46, 'Macmillans reading books', 'https://drive.google.com/file/d/1-3lD0oVPV-EzX7-XA6q25TzAVbpO3iPV/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165488/Maahir/MacMillan_s_Reading_Books_Book_V_wadcc5.jpg', 'Classic', '841 kb', '171', 'English', 'anonymous', '134', 4, 'Another Lenny Samuel mystery. Actress Gail Lane has it all, youth, beauty, money, and fame. Then she starts receiving anonymous death threats.'),
(47, 'The bible', 'https://drive.google.com/file/d/1VcttP80rW010BCMnxs9SZPRR-yGK4jiY/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165502/Maahir/The_Bible_in_its_Making_The_most_Wonderful_Book_in_the_World_gyf6eq.jpg', 'Classic', '1.99 mb', '52', 'English', 'duff,mildred', '152', 3, 'Genesis Summary?Genesis is the book of origins or beginnings. ... The rest of Genesis relates the lives of the patriarchs Abraham, Isaac, Jacob and Joseph, ending with the people of God living in Egypt. Exodus Summary?A new pharaoh enslaves the people of God, who cry out for deliverance.'),
(48, 'The book of khalid', 'https://drive.google.com/file/d/1Okr8sdPLsdJ8ulXk1Pee2SltkTz_4vpD/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165515/Maahir/The_Book_of_Khalid_awyfwh.jpg', 'Classic', '1.39 mb', '139', 'English', 'rihani', '356', 4, 'The novel, which is intensely autobiographical as Rihani himself immigrated as a child, tells the story of two boys, named Khalid and Shakib, from Baalbek in Lebanon (at the time, the Syrian province of the Ottoman Empire) who migrate together to the United States, coming by ship through Ellis Island and enduring the ...'),
(49, 'The books of china', 'https://drive.google.com/file/d/1BzpFPKzeFfTl0dYIqymrdIr_c-eI061j/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165530/Maahir/The_Books_of_Chilan_Balam_the_Prophetic_and_Historic_Records_of_the_Mayas_of_Yucatan_f0by3e.jpg', 'Classic', '701 kb', '12', 'English', 'daniel', '13', 3, 'The Four Books are: the Analects of Confucius, a book of pithy sayings attributed to Confucius and recorded by his disciples; the Mencius, a collection of political dialogues; the Doctrine of the Mean, a book that teaches the path to Confucian virtue; and.'),
(50, 'The buddhistic kingdom', 'https://drive.google.com/file/d/1BzpFPKzeFfTl0dYIqymrdIr_c-eI061j/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165541/Maahir/A_Record_of_Buddhistic_kingdoms_rdep9y.jpg', 'Classic', '690 kb', '121', 'English', 'faxian', '134', 4, 'A Record of Buddhist Kingdoms--Being an Account by the Chinese Monk Fa-Hein of Travels in India and Ceylon (Ad 399-414) in Search of the Buddhist Books of Discipline, is one of the most important source for reconstructing the life and conditions of the times.'),
(51, 'City of glasses', 'https://drive.google.com/file/d/1Bw7QI10y1wviSugYuJOGkhz4mUJ7PPsP/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165562/Maahir/City_of_Glass_novel_j2annh.jpg', 'graphic novel', '6.18 mb', '73', 'English', 'david mazzucchelli', '190', 5, 'In this book, after losing Max Lightwood (the youngest sibling), she goes through a self-conflict on her true potential as a Shadowhunter. Alec Lightwood: Jace\'s parabatai and Isabelle Lightwood\'s brother, works to reveal his true self and sexuality as it goes against the Shadowhunter society and his family.'),
(52, 'Coraline', 'https://drive.google.com/file/d/1HoCWR2mo_XXBguJFsL_KLRMEv16GRkIP/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165578/Maahir/coraline_novel_m7jjdy.jpg', 'graphic novel', '138 mb', '192', 'English', 'neil gaiman', '234', 5, 'She\'s described as being \"small for her age\", but Coraline is not afraid to face anyone; she is the most adventurous person in the book. Even though Coraline wants to never see the Other Mother again after she learns the truth about her nature, she does so anyway in order to rescue her parents.'),
(53, 'Lorna the eye of dart', 'https://drive.google.com/file/d/1lYA0o2ttN0Hdu7qN5fKZzgJNFl1S9DaN/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165591/Maahir/Lorna_the_Eye_of_Dart_an_Gor_Graphic_Novel_ndonyu.jpg', 'graphic novel', '19.6 mb', '67', 'English', 'Alfonso azpiri', '345', 4, 'Grono, a young monk on Ali-Zar finds that three probes are being sent to different planets in order to destroy all life there. Along with star warrior Lorna and Shop, a young smuggler, Grono travels to Dart-An-Gor to save the planet from its fateful destiny.'),
(54, 'The call of cthulhu', 'https://drive.google.com/file/d/1wJjQuc_m5bY43fiijXsx9l8w8dKx1Sem/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165606/Maahir/The_Call_Of_Cthulhu_czq4gn.jpg', 'graphic novel', '1.90 mb', '34', 'English', 'h.p. lovecraft', '12', 3, 'Francis Wayland Thurston tells the story of finding out about the cult of Cthulhu after reading his grand-uncle George Gammel Angell\'s papers. ... Thurston also learns of a sailor, Gustaf Johansen, who was the only survivor when his crew accidentally released the monster Cthulhu.'),
(55, 'The silver eyes', 'https://drive.google.com/file/d/1eyxb6-Zc2_4h6xBWmaCQi6shJCGjuFNy/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165619/Maahir/The_Silver_Eyes_Five_Nights_at_Freddy_s_Graphic_Novel_1_ycvkp9.jpg', 'graphic novel', '209 kb', '195', 'English', 'scott cawthon', '347', 4, 'Ten years after the horrific murders at Freddy Fazbear\'s Pizza that ripped their town apart, Charlie, whose father owned the restaurant, and her childhood friends reunite on the anniversary of the tragedy and find themselves at the old pizza place which had been locked up and abandoned for years.'),
(56, ' The Twisted History of ’70s and ’80s Horror Fiction', 'https://drive.google.com/file/d/187BDmCcXcHMUU8mSy58tFfHU0JHt6bYA/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165636/Maahir/paper_backs_from_hell_horror_dxdish.jpg', 'horror', '21.8 mb', '334', 'English', 'grady henrix', '145', 4, 'Paperbacks from Hell examines paperback horror novels of the 70s and 80s. Hendrix pays attention to trends and events that increased horror\'s readership and popularity and how the 1988 release of The Silence of the Lambs prompted publishers to shift their focus from horror to thrillers and techno-thrillers.'),
(57, 'The dread of difference', 'https://drive.google.com/file/d/1u1ExDJynlXIp_OjOhFkyWWtB8VwSGums/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165652/Maahir/The_dread_horror_mwdzjd.jpg', 'horror', '20.6 mb', '558', 'English', 'barry keith grant', '123', 5, 'The Dread of Difference demonstrates that horror is hardly a uniformly masculine discourse. ... Indeed, in this pioneering exploration of the cinema of fear, Barry Keith Grant and twenty other film critics posit that horror is always rooted in gender, particularly in anxieties about sexual difference and gender politics.'),
(58, 'The philosophy of horror', 'https://drive.google.com/file/d/1i10r0iPcv8s6AsX5-nf9yOIlKuYOvYuk/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165663/Maahir/the_philosophy_of_horror_ldzbhh.jpg', 'horror', '801 mb', '269', 'English', 'hoel carroll', '111', 5, 'In this book he discusses the nature and narrative structures of the genre, dealing with horror as a \"transmedia\" phenomenon. A fan and serious student of the horror genre, Carroll brings to bear his comprehensive knowledge of obscure and forgotten works, as well as of the horror masterpieces.'),
(59, 'The valan court', 'https://drive.google.com/file/d/1bzmLCnCPYOWp6Q5xSvD4H5aTkH0QKxmj/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165677/Maahir/the_valan_court_mp40ss.jpg', 'horror', '1.08 mb', '227', 'English', 'ryan cagle', '578', 5, 'The Valancourt Book of World Horror Stories brings us a collection of tales by outstanding writers from all over the world. These stories are by turns unsettling, violent, strange, and beautiful -- all the ingredients of great horror stories, from voices and perspectives we have lived too long without.?'),
(60, 'What fears become an anthology', 'https://drive.google.com/file/d/1zJyRTMuMxHevMfniWFow16iCtCwnla2F/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165690/Maahir/what_fears_become_dyjtwo.jpg', 'horror', '2.03 mb', '409', 'English', 'jeani reactor', '697', 5, 'An Anthology from The Horror Zine [Little, Bentley, Anthony, Piers, Nicholson, Scott, ... Do I review them individually? ... I think I will just say that this book will entertain the deepest fears hidden in the corners of the psyche.'),
(61, 'Dreaming of dreaming', 'https://drive.google.com/file/d/1dBHMbVtu9Tf4PEZSrS1yJYlXow4A2qwL/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165711/Maahir/Dreaming_of_Dreaming_Poetry_by_Peter_E._Williams_uwq9fj.jpg', 'poetry', '214 kb', '26', 'English', 'mccann,tim', '97', 3, 'the more time you have to sleep, the more dream fodder you\'ll have to explore. ... author Robert A. Johnson argues that the experiences we have in a dream ... By relying on research and case studies to describe how dreams work and ...'),
(62, 'Poetry', 'https://drive.google.com/file/d/1nWblc07BjiuT69ThIDcS0p3onJPwb5aZ/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165726/Maahir/Poetry_zaxx9d.jpg', 'poetry', '413 kb', '14', 'English', 'Arthur quiller-coach', '16', 3, 'This is not a book of poems, but rather an exploration of the poet as a creator who is able to reconcile (and translate for the rest of us) his inner harmony with the ...'),
(63, 'Sleep- book some of the poetry of slumber', 'https://drive.google.com/file/d/1Gl9m-YnwttLDdR9QIRUXrKmzWclNUQnG/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165735/Maahir/Sleep-Book_Some_of_the_Poetry_of_Slumber_qsjwrn.jpg', 'poetry', '189 kb', '2', 'English', 'various', '12', 3, 'My sleep had been embroidered with dim dreams,My soul had been a lawn besprinkled o\'erWith flowers, and stirring shades of baffled beams.'),
(64, 'The future of english poetry', 'https://drive.google.com/file/d/15m1RV1i3nTmosT4f1Bk0uLVhSzr7F-wK/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165747/Maahir/The_Future_of_English_Poetry_wokau3.jpg', 'poetry', '289 kb', '15', 'English', 'gosse,edmund', '34', 4, 'This work has been selected by scholars as being culturally important, and is part of the knowledge base of civilization as we know it. This work was reproduced from the original artifact, and remains as true to the original work as possible. Therefore, you will see the original copyright references, library stamps (as most of these works have been housed in our most important libraries around the world), and other notations in the work.'),
(65, 'The purple cow', 'https://drive.google.com/file/d/1h-_nnQnC1JDMawedMr_rfOL88_x3zM3i/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165757/Maahir/The_Purple_Cow_kqpefv.jpg', 'poetry', '2.95 mb', '30', 'English', 'burgess,gelett', '68', 3, 'n Purple Cow, Seth Godin urges you to put a Purple Cow into everything you build, and everything you do, to create something truly noticeable. It\'s a manifesto for marketers who want to help create products that are worth marketing in the first place.'),
(66, 'Confidences talks with a young girl', 'https://drive.google.com/file/d/1wd0d6v_BIQgX4BMymeAFRgcdERVsesNF/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165774/Maahir/Confidences_Talks_With_a_Young_Girl_Concerning_Herself_vorwrw.jpg', 'self help', '281 kb', '18', 'English', 'lowry,edith', '98', 4, 'f you have married a young lady whose education has been ... the axioms and precepts which we shall develop in the second part of this book. ... curious than boys, their secret meetings and their conversations, which all the art of ... the moral reflections and the corrupting confidences of these young girls?'),
(67, 'In  darkest-england and the way out', 'https://drive.google.com/file/d/1lyFFMyKFIPtOB337GZxnCArmkRBmd4gZ/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165782/Maahir/In_Darkest_England_and_the_Way_Out_adusia.jpg', 'self help', '830 kb', '101', 'English', 'booth, william', '121', 3, '\"In Darkest England and the Way Out,\" is an awful yet fascinating book (or rather a strategic, audacious plan) by one man and a vision to change a nation of 3 million destitute who were enslaved in the 1890\'s in darkest England. One tenth of the population at that time.'),
(68, 'Life of luther', 'https://drive.google.com/file/d/15fWvjGkeiBthlx9JzjiLTASFMSIocX8w/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165794/Maahir/Life_of_Luther_ktccv1.jpg', 'self help', '1.36 mb', '252', 'English', 'koestlin,julius', '231', 5, 'A historic and comprehensive biography of early Christianity\'s most influential leader of the Protestant Reformation, Martin Luther. A historic and comprehensive biography of early Christianity\'s most influential leader of the Protestant Reformation, Martin Luther.'),
(69, 'Punch or the london charivari', 'https://drive.google.com/file/d/18wbop-uKnnrRWZOKJH3QTUdyqFWNT4zG/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165803/Maahir/punch_or_the_london_charivari_cwy1na.png', 'self help', '1.89 mb', '34', 'English', 'Seaman,owmen', '98', 4, 'Punch, or The London Charivari was a British weekly magazine of humour and satire established in 1841 by Henry Mayhew and wood-engraver Ebenezer Landells. Historically, it was most influential in the 1840s and 1850s, when it helped to coin the term \"cartoon\" in its modern sense as a humorous illustration.'),
(70, 'Self hypnosis', 'https://drive.google.com/file/d/1gK_Z21JLABGBDJNII54o0VZ4Sx9DgYz0/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165812/Maahir/self_hypnosis_eyl06v.jpg', 'self help', '1.00 mb', '61', 'English', 'powers,melvin', '134', 4, 'But Instant Self-Hypnosis is the only self-hypnosis book that allows you to hypnotize yourself as you read, with your eyes wide open, without putting down the book. The author\'s fail-proof method allows you to put yourself into a hypnotic state and then use that state to improve your life in myriad ways.'),
(71, '100 years of the best american short stories', 'https://drive.google.com/file/d/1Bauy82SZP7_k7b9XjOE56MiaDCZhwG1e/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165826/Maahir/100_years_of_the_best_American_short_stories_i4zlev.jpg', 'short storys', '4.93 mb', '779', 'English', 'heidi pitlor', '289', 5, 'Series editor Heidi Pitlor recounts behind-the-scenes anecdotes and examines, decade by decade, the trends captured over a hundred years. Together, the stories and commentary offer an extraordinary guided tour through a century of literature with what Moore calls ?all its wildnesses of character and voice.?'),
(72, 'More short stories', 'https://drive.google.com/file/d/1ev0xWpihRVLUcOMC8fsBQ0WhemKrtEjH/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165853/Maahir/More_Short_Stories_for_Children_igcgh7.jpg', 'short storys', '3,44 mb', '115', 'English', 'jagdish joshi', '321', 4, 'Ramayana in Pictures, and HOW MUNIA FOUND GOLD, and more on ThriftBooks.com. ... We use Cookies to collect information when you visit our site. You can learn more ... A Voice In The Jungle 8123720041 Book Cover. A Voice In The Jungle.'),
(73, 'Short story classic', 'https://drive.google.com/file/d/108fbonHL6fZwcNrbKVAclOjUFREfkTaX/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165865/Maahir/Short_Story_Classics_American_Vol._2_ayqqu4.jpg', 'short storys', '1.03 mb', '112', 'English', 'patten william', '234', 4, 'Then he saw, an indefinite distance beyond him, burning like red-hot iron through the darkness, a little scarlet or crimson gleam, as of a lighted cigar.'),
(74, 'The best british short story in 1922', 'https://drive.google.com/file/d/121b-O5vNbp6jdwzdpuUszBwXQUg41wIe/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165877/Maahir/The_Best_British_Short_Stories_of_1922_lddeha.jpg', 'short storys', '1.08 mb', '191', 'English', 'Aumonier stacy', '112', 3, '1921, 1922. In the public bar of the Wagtail, in Wapping, four men and a woman were drinking beer and discussing diseases. It was not a pretty subject, and the company was certainly not a handsome one.'),
(75, 'The complete stort story of ernest and heimengway', 'https://drive.google.com/file/d/1YSuqjtxxEMlNAnykNcbJWIsv-NFllHDQ/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165887/Maahir/The_Complete_Short_Stories_of_Ernest_Hemingway_tsm6ij.jpg', 'short storys', '3.20mb', '811', 'English', 'charles scribner jr.', '121', 5, 'This collection demonstrates Hemingway\'s ability to write beautiful prose for each distinct story, with plots that range from experiences of World War II to beautifully touching moments between a father and son. For Hemingway fans, The Complete Short Stories is an invaluable treasury.'),
(76, 'The first essay of women rights', 'https://drive.google.com/file/d/1aEp6yNR55OVmIRueWyyQmnycV3u2M-Ev/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165938/Maahir/The_First_Essay_on_the_Political_Rights_of_Women_p8dljz.jpg', 'women\'s friction', '211 kb', '7', 'English', ' jean antoine nicolas de caritat', '54', 4, 'Women\'s rights are the rights and entitlements claimed for women and girls worldwide. ... Further information: Women in Greece ... This tutelage had limited female activity but by the first century to sixth century BCE, tutelage ... by American feminist Agnes Smedley in her book Portraits of Chinese Women in Revolution.'),
(77, 'Women of america', 'https://drive.google.com/file/d/1c74pqKjAF7Dh1H9THrgT__qylHHQ1RRF/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165954/Maahir/Women_of_America_Woman_xo9yuq.jpg', 'women\'s friction', '1.92 mb', '113', 'English', 'larus,john rouse', '760', 5, 'From the Back Cover. From colonial to modern-day times this narrative history, incorporating first-person accounts, traces the development of women\'s roles in America. Against the backdrop of major historical events and movements, the authors examine the issues that changed the roles and lives of women in our society.'),
(78, 'Women of england', 'https://drive.google.com/file/d/1BqDtCmurzbJjlqIpbBjru3z_z8ki6ZEz/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165963/Maahir/Women_of_England_qd19cg.jpg', 'women\'s friction', '2.31 mb', '146', 'English', 'James,Bartlett burleigh', '690', 5, 'women have a religious duty to bring up the next generation properly, instilling moral values in young people for the benefit of society at large. The pages shown here are the opening of The Women of England, published in 1839.'),
(79, 'Women of the country', 'https://drive.google.com/file/d/1UvXUPKb7vNNQlZDhOYMxVGZaoVA-j7wH/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165978/Maahir/Women_of_the_Country_rn0otw.jpg', 'women\'s friction', '329 kb', '66', 'English', 'Bone,gertrude', '465', 5, 'In the Country of Women? is at its core an extended letter to her three daughters, Gaila, Delphine and Rosette Sims. This book, Straight writes, will be about the generations of women ? from both Straight\'s and their father Dwayne Sims\'s sides ? who have made their lives possible.'),
(80, 'Women of the teuton', 'https://drive.google.com/file/d/15VyImpWsLFchpehM_T6gOeyTMGS_snUS/view?usp=sharing', 'https://res.cloudinary.com/hemasri-12/image/upload/v1619165991/Maahir/Women_of_the_Teutonic_Nations_ouqczq.jpg', 'women\'s friction', '2.15 mb', '136', 'English', 'schoenfeld hermann', '395', 5, 'The Teutons were an ancient tribe mentioned by Roman authors. They are generally classified ... When their request was denied, the Teutonic women slew their own children.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `book_data`
--
ALTER TABLE `book_data`
  ADD PRIMARY KEY (`book_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `book_data`
--
ALTER TABLE `book_data`
  MODIFY `book_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
